# Generated by Django 3.2.2 on 2021-05-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='postions',
            new_name='positions',
        ),
    ]
